<a href="https://colab.research.google.com/github/RICHAR-SL/nump/blob/main/ejercicio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy, ciencia de datos

In [1]:
import numpy as np


In [2]:
#1 DIMENSION
array_1d=np.array([10,20,30])

print("1 Dimencion",array_1d)
#2 Dimension

array_2d=np.array([(1,2,3,4,5,6,7,8,9,10),(-1,-2,-3,-4,-5,-6,-7,-8,-9,-10)])

print("2 Dimension", array_2d)



1 Dimencion [10 20 30]
2 Dimension [[  1   2   3   4   5   6   7   8   9  10]
 [ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]]


In [3]:
print("3 dimension")
array_3d=np.array([(1,2,3),(-1,-2,-3),(8,9,10)],dtype=str)


3 dimension


In [4]:
print(array_3d)

[['1' '2' '3']
 ['-1' '-2' '-3']
 ['8' '9' '10']]


arrays con ceros tres filas y 4 columnas


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#dos mineciones
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS CON INTERVALOS


In [7]:
np.arange(20,30,40)

array([20])

In [8]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
#arrays con intervalos y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [10]:
#arrays con valores dados
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
#Array matriz identidad, diagonal del unos

np.eye(3,3,-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [12]:
#array valores aleatorios

np.random.random((4,3))

array([[0.0497736 , 0.36944189, 0.19609556],
       [0.5792934 , 0.44436621, 0.87252699],
       [0.38924694, 0.69032289, 0.25130436],
       [0.44975344, 0.33814871, 0.91987695]])

In [13]:
#arrays de numeros vacios
np.empty((4,3))

array([[0.0497736 , 0.36944189, 0.19609556],
       [0.5792934 , 0.44436621, 0.87252699],
       [0.38924694, 0.69032289, 0.25130436],
       [0.44975344, 0.33814871, 0.91987695]])

In [14]:
#Grabar
np.save('mi_arrays',np.random.random((3,3)))

In [15]:
#Cargar
mi_arrays=np.load('mi_arrays.npy')
print(mi_arrays)


[[0.27377934 0.94290018 0.42413567]
 [0.82238554 0.85681162 0.23510298]
 [0.07744396 0.63462148 0.32841452]]


In [16]:
#Grabar
np.save('mi_array_3d',array_3d)
#Cargar
mi_3d=np.load('mi_array_3d.npy')
print(mi_3d)

[['1' '2' '3']
 ['-1' '-2' '-3']
 ['8' '9' '10']]


Grabar y cargar ficheros de textos


In [17]:
#grabar el fichero
np.savetxt('hola mundo.txt', array_2d,delimiter=" ")

In [18]:
#cargar el fichero hola mundo
np.loadtxt('hola mundo.txt')

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.]])

Ejercicios


Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista y la muestre por pantalla.

In [19]:

materias=np.array(['Matemárica','Física','Química','Historia','Lenguaje'])
#guardar
materias=np.save('ejer1',materias)


In [20]:
np.load('ejer1.npy')

array(['Matemárica', 'Física', 'Química', 'Historia', 'Lenguaje'],
      dtype='<U10')

Ejercicio 2
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista y la muestre por pantalla el mensaje Yo estudio
<asignatura>, donde <asignatura> es cada una de las asignaturas de la lista.

In [21]:
cursos=np.array(['Matemárica','Física','Química','Historia','Lenguaje'])

longitud = len(cursos)
print(f"La longitud de la lista es: {longitud}")
curso_estudio=[]
for i in range(longitud):
    mensaje = f"Yo estudio: {cursos[i]}"
    print(mensaje)
    curso_estudio.append(mensaje)




#guardar
cursos=np.save('ejer2',curso_estudio)



La longitud de la lista es: 5
Yo estudio: Matemárica
Yo estudio: Física
Yo estudio: Química
Yo estudio: Historia
Yo estudio: Lenguaje


In [22]:
np.load('ejer2.npy')

array(['Yo estudio: Matemárica', 'Yo estudio: Física',
       'Yo estudio: Química', 'Yo estudio: Historia',
       'Yo estudio: Lenguaje'], dtype='<U22')

Ejercicio 3
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada
asignatura, y después las muestre por pantalla con el mensaje En 'asignatura' has sacado 'nota'
donde 'asignatura' es cada una des las asignaturas de la lista y 'nota' cada una de las
correspondientes notas introducidas por el usuario.

In [24]:

cursos = np.array(['Matemática', 'Física', 'Química', 'Historia', 'Lenguaje'])

longitud = len(cursos)
notas = []
curso_nota = []

for i in range(longitud):
    mensaje = input(f"Nota en {cursos[i]}: ")
    notas.append(mensaje)

for j in range(longitud):
    notas_texto = f"En {cursos[j]} sacaste : {notas[j]}"
    curso_nota.append(notas_texto)

#guardar
cursos=np.save('ejer3',curso_nota)


Nota en Matemática: 5
Nota en Física: 4
Nota en Química: 11
Nota en Historia: 45
Nota en Lenguaje: 5


In [25]:
#cargar
np.load('ejer3.npy')

array(['En Matemática sacaste : 5', 'En Física sacaste : 4',
       'En Química sacaste : 11', 'En Historia sacaste : 45',
       'En Lenguaje sacaste : 5'], dtype='<U25')

Ejercicio 4
Escribir un programa que pregunte al usuario los números ganadores de la lotería primitiva, los
almacene en una lista y los muestre por pantalla ordenados de menor a mayor.

In [ ]:
numeros_ganadores = []
print("Introduce los números ganadores de la lotería primitiva:")

for i in range(6):
    while True:
            num = int(input(f"Número {i+1}: "))
            if num < 1 or num > 50:
                print("Por favor, introduce un número entre 1 y 49.")
            else:
                numeros_ganadores.append(num)
                break


# Ordenar la lista de menor a mayor
numeros_ganadores.sort()
print(numeros_ganadores)
#guardar
loteria=np.save('ejer4',numeros_ganadores)


In [ ]:
#cargar
np.load('ejer4.npy')

Ejercicio 5
Escribir un programa que almacene en una lista los números del 1 al 10 y los muestre por pantalla
en orden inverso separados por comas.


In [ ]:
# Crear la lista con números del 1 al 10

numeros =np.array(range(1, 11))

numeros_invertidos=numeros[::-1]

# Convertir los números a strings para unirlos con comas
numeros_str = [str(num) for num in numeros_invertidos]

# Mostrar los números separados por comas
print(", ".join(numeros_str))

#guardar
invertidos=np.save('ejer5',numeros_str)

In [ ]:
#cargar
np.load('ejer5.npy')

Ejercicio 6
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada
asignatura y elimine de la lista las asignaturas aprobadas. Al final el programa debe mostrar por
pantalla las asignaturas que el usuario tiene que repetir.


In [43]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

# Recolectar las notas
for asignatura in asignaturas:
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("La nota debe estar entre 0 y 20.")
        except ValueError:
            print("Por favor, ingresa un número válido.")

# Determinar qué asignaturas se deben repetir
asignaturas_a_repetir = []

for i in range(len(notas)):
    if notas[i] <= 10:
        asignaturas_a_repetir.append(f"{asignaturas[i]} (Nota: {notas[i]})")

# Mostrar resultado
print("\nDebes repetir las siguientes asignaturas:")
if asignaturas_a_repetir:
    for rep in asignaturas_a_repetir:
        print(f"- {rep}")
else:
    print("No debes repetir ninguna asignatura.")



# Guardar en archivo numpy
np.save('ejer6', asignaturas_a_repetir)

¿Qué nota has sacado en Matemáticas? 1
¿Qué nota has sacado en Física? 2
¿Qué nota has sacado en Química? 20
¿Qué nota has sacado en Historia? 10
¿Qué nota has sacado en Lengua? 11

Debes repetir las siguientes asignaturas:
- Matemáticas (Nota: 1.0)
- Física (Nota: 2.0)
- Historia (Nota: 10.0)


In [49]:
# Cargar archivo y mostrar contenido
np.load('ejer6.npy')

array(['Matemáticas (Nota: 1.0)', 'Física (Nota: 2.0)',
       'Historia (Nota: 10.0)'], dtype='<U23')

Ejercicio 7
Escribir un programa que almacene el abecedario en una lista, elimine de la lista las letras que
ocupen posiciones múltiplos de 3, y muestre por pantalla la lista resultante.

In [54]:

import string

abecedario = list(string.ascii_lowercase)
resultado = [letra for i, letra in enumerate(abecedario, start=1) if i % 3 != 0]

np.save('ej7.npy', np.array(resultado))



In [55]:
cargado = np.load('ej7.npy')
print("Resultado Ejercicio 7:", list(cargado))

Resultado Ejercicio 7: [np.str_('a'), np.str_('b'), np.str_('d'), np.str_('e'), np.str_('g'), np.str_('h'), np.str_('j'), np.str_('k'), np.str_('m'), np.str_('n'), np.str_('p'), np.str_('q'), np.str_('s'), np.str_('t'), np.str_('v'), np.str_('w'), np.str_('y'), np.str_('z')]


Ejercicio 8
Escribir un programa que pida al usuario una palabra y muestre por pantalla si es un palíndromo

In [64]:


palabra = input("Introduce una palabra: ").lower()
es_palindromo =np.array( palabra == palabra[::-1])

np.save('ej8.npy', es_palindromo)


print("¿Es palíndromo?", "Sí" if resultado else "No")


Introduce una palabra: anilina
¿Es palíndromo? Sí


In [65]:
 np.load('ej8.npy')


array(True)

Ejercicio 9
Escribir un programa que pida al usuario una palabra y muestre por pantalla el número de veces
que contiene cada vocal.


In [87]:


palabra = input("Introduce una palabra: ").lower()
vocales = "aeiou"
conteo=[]
for v in vocales:
  conteo.append(palabra.count(v))



np.save('ej9.npy',np.array(conteo))

Introduce una palabra: holaa


In [88]:
cargadoooo = np.load('ej9.npy')
print("Cantidad de vocales (a, e, i, o, u):", cargadoooo)

Cantidad de vocales (a, e, i, o, u): [2 0 0 1 0]


Ejercicio 10
Escribir un programa que almacene en una lista los siguientes precios, 50, 75, 46, 22, 80, 65, 8, y
muestre por pantalla el menor y el mayor de los precios

In [89]:


precios = np.array([50, 75, 46, 22, 80, 65, 8])
np.save('ej10.npy', precios)




In [90]:
cargado = np.load('ej10.npy')
print("Menor precio:", np.min(cargado))
print("Mayor precio:", np.max(cargado))

Menor precio: 8
Mayor precio: 80


Ejercicio 11
Escribir un programa que almacene los vectores (1,2,3) y (-1,0,2) en dos listas y muestre por
pantalla su producto escalar.


In [97]:


v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 2])
producto = np.dot(v1, v2)
producto=np.array(producto)
np.save('ej11.npy',producto )



In [98]:
cargado = np.load('ej11.npy')
print("Producto escalar:", cargado)

Producto escalar: 7


Ejercicio 12
Escribir un programa que almacene las matrices en una lista y muestre por pantalla su producto.
Nota: Para representar matrices mediante listas usar listas anidadas, representando cada vector
fila en una lista.

In [100]:


matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[2, 0], [1, 2]])
producto = np.matmul(matriz1, matriz2)

np.save('ej12.npy', producto)



In [101]:
cargado = np.load('ej12.npy')
print("Producto de matrices:\n", cargado)

Producto de matrices:
 [[ 4  4]
 [10  8]]


Ejercicio 13
Escribir un programa que pregunte por una muestra de números, separados por comas, los guarde
en una lista y muestre por pantalla su media y desviación típica.

In [105]:
# Paso 1: Pedir al usuario los números separados por comas
entrada = input("Introduce números separados por comas: ")
# Paso 2: Separar los números y convertirlos en flotantes
lista_numeros = entrada.split(",")  # convierte "10,20,30" → ["10", "20", "30"]
numeros = []
for x in lista_numeros:
    numeros.append(float(x))  # convierte string a float
numeros_array = np.array(numeros)
media = np.mean(numeros_array)
desviacion = np.std(numeros_array)

resultado = np.array([media, desviacion])

np.save('ej13.npy', resultado)




Introduce números separados por comas: 2,2,2,2,5,5,4,1,6,2,4


In [106]:
# Cargar y mostrar el resultado
cargado = np.load('ej13.npy')
print(f"Media: {cargado[0]:.2f}")
print(f"Desviación típica: {cargado[1]:.2f}")

Media: 3.18
Desviación típica: 1.59
