<a href="https://colab.research.google.com/github/RICHAR-SL/nump/blob/main/ejercicio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy, ciencia de datos

In [1]:
import numpy as np


In [2]:
#1 DIMENSION
array_1d=np.array([10,20,30])

print("1 Dimencion",array_1d)
#2 Dimension

array_2d=np.array([(1,2,3,4,5,6,7,8,9,10),(-1,-2,-3,-4,-5,-6,-7,-8,-9,-10)])

print("2 Dimension", array_2d)



1 Dimencion [10 20 30]
2 Dimension [[  1   2   3   4   5   6   7   8   9  10]
 [ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]]


In [3]:
print("3 dimension")
array_3d=np.array([(1,2,3),(-1,-2,-3),(8,9,10)],dtype=str)


3 dimension


In [4]:
print(array_3d)

[['1' '2' '3']
 ['-1' '-2' '-3']
 ['8' '9' '10']]


arrays con ceros tres filas y 4 columnas


In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#dos mineciones
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

ARRAYS CON INTERVALOS


In [7]:
np.arange(20,30,40)

array([20])

In [8]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [9]:
#arrays con intervalos y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [10]:
#arrays con valores dados
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
#Array matriz identidad, diagonal del unos

np.eye(3,3,-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [12]:
#array valores aleatorios

np.random.random((4,3))

array([[0.96314797, 0.03746454, 0.77623462],
       [0.15284365, 0.92153762, 0.7106193 ],
       [0.69123094, 0.40492844, 0.25856214],
       [0.18440206, 0.02332072, 0.8418274 ]])

In [13]:
#arrays de numeros vacios
np.empty((4,3))

array([[0.96314797, 0.03746454, 0.77623462],
       [0.15284365, 0.92153762, 0.7106193 ],
       [0.69123094, 0.40492844, 0.25856214],
       [0.18440206, 0.02332072, 0.8418274 ]])

In [14]:
#Grabar
np.save('mi_arrays',np.random.random((3,3)))

In [15]:
#Cargar
mi_arrays=np.load('mi_arrays.npy')
print(mi_arrays)


[[0.68833199 0.46121165 0.74943783]
 [0.93537085 0.410448   0.48477171]
 [0.61939511 0.26852232 0.19842239]]


In [16]:
#Grabar
np.save('mi_array_3d',array_3d)
#Cargar
mi_3d=np.load('mi_array_3d.npy')
print(mi_3d)

[['1' '2' '3']
 ['-1' '-2' '-3']
 ['8' '9' '10']]


Grabar y cargar ficheros de textos


In [17]:
#grabar el fichero
np.savetxt('hola mundo.txt', array_2d,delimiter=" ")

In [18]:
#cargar el fichero hola mundo
np.loadtxt('hola mundo.txt')

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.]])

Ejercicios


Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista y la muestre por pantalla.

In [19]:

materias=np.array(['Matemárica','Física','Química','Historia','Lenguaje'])
#guardar
materias=np.save('ejer1',materias)


In [20]:
np.load('ejer1.npy')

array(['Matemárica', 'Física', 'Química', 'Historia', 'Lenguaje'],
      dtype='<U10')

Ejercicio 2
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista y la muestre por pantalla el mensaje Yo estudio
<asignatura>, donde <asignatura> es cada una de las asignaturas de la lista.

In [21]:
cursos=np.array(['Matemárica','Física','Química','Historia','Lenguaje'])

longitud = len(cursos)
print(f"La longitud de la lista es: {longitud}")
curso_estudio=[]
for i in range(longitud):
    mensaje = f"Yo estudio: {cursos[i]}"
    print(mensaje)
    curso_estudio.append(mensaje)




#guardar
cursos=np.save('ejer2',curso_estudio)



La longitud de la lista es: 5
Yo estudio: Matemárica
Yo estudio: Física
Yo estudio: Química
Yo estudio: Historia
Yo estudio: Lenguaje


In [22]:
np.load('ejer2.npy')

array(['Yo estudio: Matemárica', 'Yo estudio: Física',
       'Yo estudio: Química', 'Yo estudio: Historia',
       'Yo estudio: Lenguaje'], dtype='<U22')

Ejercicio 3
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada
asignatura, y después las muestre por pantalla con el mensaje En 'asignatura' has sacado 'nota'
donde 'asignatura' es cada una des las asignaturas de la lista y 'nota' cada una de las
correspondientes notas introducidas por el usuario.

In [23]:

cursos = np.array(['Matemática', 'Física', 'Química', 'Historia', 'Lenguaje'])

longitud = len(cursos)
notas = []
curso_nota = []

for i in range(longitud):
    mensaje = input(f"Nota en {cursos[i]}: ")
    notas.append(mensaje)

for j in range(longitud):
    notas_texto = f"En {cursos[j]} sacaste : {notas[j]}"
    curso_nota.append(notas_texto)

#guardar
cursos=np.save('ejer3',curso_nota)


Nota en Matemática: 4
Nota en Física: 5
Nota en Química: 7
Nota en Historia: 8
Nota en Lenguaje: 5


In [24]:
#cargar
np.load('ejer3.npy')

array(['En Matemática sacaste : 4', 'En Física sacaste : 5',
       'En Química sacaste : 7', 'En Historia sacaste : 8',
       'En Lenguaje sacaste : 5'], dtype='<U25')

Ejercicio 4
Escribir un programa que pregunte al usuario los números ganadores de la lotería primitiva, los
almacene en una lista y los muestre por pantalla ordenados de menor a mayor.

In [25]:
numeros_ganadores = []
print("Introduce los números ganadores de la lotería primitiva:")

for i in range(6):
    while True:
            num = int(input(f"Número {i+1}: "))
            if num < 1 or num > 50:
                print("Por favor, introduce un número entre 1 y 49.")
            else:
                numeros_ganadores.append(num)
                break


# Ordenar la lista de menor a mayor
numeros_ganadores.sort()
print(numeros_ganadores)
#guardar
loteria=np.save('ejer4',numeros_ganadores)


Introduce los números ganadores de la lotería primitiva:
Número 1: 2
Número 2: 1
Número 3: 5
Número 4: 4
Número 5: 8
Número 6: 5
[1, 2, 4, 5, 5, 8]


In [26]:
#cargar
np.load('ejer4.npy')

array([1, 2, 4, 5, 5, 8])

Ejercicio 5
Escribir un programa que almacene en una lista los números del 1 al 10 y los muestre por pantalla
en orden inverso separados por comas.


In [27]:
# Crear la lista con números del 1 al 10

numeros =np.array(range(1, 11))

numeros_invertidos=numeros[::-1]

# Convertir los números a strings para unirlos con comas
numeros_str = [str(num) for num in numeros_invertidos]

# Mostrar los números separados por comas
print(", ".join(numeros_str))

#guardar
invertidos=np.save('ejer5',numeros_str)

10, 9, 8, 7, 6, 5, 4, 3, 2, 1


In [28]:
#cargar
np.load('ejer5.npy')

array(['10', '9', '8', '7', '6', '5', '4', '3', '2', '1'], dtype='<U2')

Ejercicio 6
Escribir un programa que almacene las asignaturas de un curso (por ejemplo Matemáticas, Física,
Química, Historia y Lengua) en una lista, pregunte al usuario la nota que ha sacado en cada
asignatura y elimine de la lista las asignaturas aprobadas. Al final el programa debe mostrar por
pantalla las asignaturas que el usuario tiene que repetir.


In [29]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

# Recolectar las notas
for asignatura in asignaturas:
    while True:
        try:
            nota = float(input(f"¿Qué nota has sacado en {asignatura}? "))
            if 0 <= nota <= 20:
                notas.append(nota)
                break
            else:
                print("La nota debe estar entre 0 y 20.")
        except ValueError:
            print("Por favor, ingresa un número válido.")

# Determinar qué asignaturas se deben repetir
asignaturas_a_repetir = []

for i in range(len(notas)):
    if notas[i] <= 10:
        asignaturas_a_repetir.append(f"{asignaturas[i]} (Nota: {notas[i]})")

# Mostrar resultado
print("\nDebes repetir las siguientes asignaturas:")
if asignaturas_a_repetir:
    for rep in asignaturas_a_repetir:
        print(f"- {rep}")
else:
    print("No debes repetir ninguna asignatura.")



# Guardar en archivo numpy
np.save('ejer6', asignaturas_a_repetir)

¿Qué nota has sacado en Matemáticas? 2
¿Qué nota has sacado en Física? 5
¿Qué nota has sacado en Química? 4
¿Qué nota has sacado en Historia? 24
La nota debe estar entre 0 y 20.
¿Qué nota has sacado en Historia? 5
¿Qué nota has sacado en Lengua? 5

Debes repetir las siguientes asignaturas:
- Matemáticas (Nota: 2.0)
- Física (Nota: 5.0)
- Química (Nota: 4.0)
- Historia (Nota: 5.0)
- Lengua (Nota: 5.0)


In [30]:
# Cargar archivo y mostrar contenido
np.load('ejer6.npy')

array(['Matemáticas (Nota: 2.0)', 'Física (Nota: 5.0)',
       'Química (Nota: 4.0)', 'Historia (Nota: 5.0)',
       'Lengua (Nota: 5.0)'], dtype='<U23')

Ejercicio 7
Escribir un programa que almacene el abecedario en una lista, elimine de la lista las letras que
ocupen posiciones múltiplos de 3, y muestre por pantalla la lista resultante.

In [31]:

import string

abecedario = list(string.ascii_lowercase)
resultado = [letra for i, letra in enumerate(abecedario, start=1) if i % 3 != 0]

np.save('ej7.npy', np.array(resultado))



In [32]:
cargado = np.load('ej7.npy')
print("Resultado Ejercicio 7:", list(cargado))

Resultado Ejercicio 7: [np.str_('a'), np.str_('b'), np.str_('d'), np.str_('e'), np.str_('g'), np.str_('h'), np.str_('j'), np.str_('k'), np.str_('m'), np.str_('n'), np.str_('p'), np.str_('q'), np.str_('s'), np.str_('t'), np.str_('v'), np.str_('w'), np.str_('y'), np.str_('z')]


Ejercicio 8
Escribir un programa que pida al usuario una palabra y muestre por pantalla si es un palíndromo

In [33]:


palabra = input("Introduce una palabra: ").lower()
es_palindromo =np.array( palabra == palabra[::-1])

np.save('ej8.npy', es_palindromo)


print("¿Es palíndromo?", "Sí" if resultado else "No")


Introduce una palabra: 6
¿Es palíndromo? Sí


In [34]:
 np.load('ej8.npy')


array(True)

Ejercicio 9
Escribir un programa que pida al usuario una palabra y muestre por pantalla el número de veces
que contiene cada vocal.


In [35]:


palabra = input("Introduce una palabra: ").lower()
vocales = "aeiou"
conteo=[]
for v in vocales:
  conteo.append(palabra.count(v))



np.save('ej9.npy',np.array(conteo))

Introduce una palabra: 8


In [36]:
cargadoooo = np.load('ej9.npy')
print("Cantidad de vocales (a, e, i, o, u):", cargadoooo)

Cantidad de vocales (a, e, i, o, u): [0 0 0 0 0]


Ejercicio 10
Escribir un programa que almacene en una lista los siguientes precios, 50, 75, 46, 22, 80, 65, 8, y
muestre por pantalla el menor y el mayor de los precios

In [37]:


precios = np.array([50, 75, 46, 22, 80, 65, 8])
np.save('ej10.npy', precios)




In [38]:
cargado = np.load('ej10.npy')
print("Menor precio:", np.min(cargado))
print("Mayor precio:", np.max(cargado))

Menor precio: 8
Mayor precio: 80


Ejercicio 11
Escribir un programa que almacene los vectores (1,2,3) y (-1,0,2) en dos listas y muestre por
pantalla su producto escalar.


In [39]:


v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 2])
producto = np.dot(v1, v2)
producto=np.array(producto)
np.save('ej11.npy',producto )



In [40]:
cargado = np.load('ej11.npy')
print("Producto escalar:", cargado)

Producto escalar: 5


Ejercicio 12
Escribir un programa que almacene las matrices en una lista y muestre por pantalla su producto.
Nota: Para representar matrices mediante listas usar listas anidadas, representando cada vector
fila en una lista.

In [41]:


matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[2, 0], [1, 2]])
producto = np.matmul(matriz1, matriz2)

np.save('ej12.npy', producto)



In [42]:
cargado = np.load('ej12.npy')
print("Producto de matrices:\n", cargado)

Producto de matrices:
 [[ 4  4]
 [10  8]]


Ejercicio 13
Escribir un programa que pregunte por una muestra de números, separados por comas, los guarde
en una lista y muestre por pantalla su media y desviación típica.

In [43]:
# Paso 1: Pedir al usuario los números separados por comas
entrada = input("Introduce números separados por comas: ")
# Paso 2: Separar los números y convertirlos en flotantes
lista_numeros = entrada.split(",")  # convierte "10,20,30" → ["10", "20", "30"]
numeros = []
for x in lista_numeros:
    numeros.append(float(x))  # convierte string a float
numeros_array = np.array(numeros)
media = np.mean(numeros_array)
desviacion = np.std(numeros_array)

resultado = np.array([media, desviacion])

np.save('ej13.npy', resultado)




Introduce números separados por comas: 7


In [44]:
# Cargar y mostrar el resultado
cargado = np.load('ej13.npy')
print(f"Media: {cargado[0]:.2f}")
print(f"Desviación típica: {cargado[1]:.2f}")

Media: 7.00
Desviación típica: 0.00


Tipos de datos


In [45]:
# ENTEROS
np.int64

# DECIMAL, FLOTANTES
np.float64

#complejos
np.complex64

#BOOLEANOS
np.bool
np.bool_

#OBJETOS
np.object_

#CADENA DE TEXTO
np.strings

#------------------------------#
np.bytes_


numpy.bytes_

PROPIEDADES Y CARACTERISTICAS DE ENTEROS

In [46]:
array_3d.shape

(3, 3)

In [47]:
#longitud-el mayor de un array
len(array_2d)

2

In [52]:
#numeros de dimensiones
array_2d.ndim

2

In [83]:
array_5d = np.array([[[[[(2,3,6)], [(4,5,4)], [(1,2,1)], [(6,3,7)], [(7,8,9)]],[[(2,3,6)], [(4,5,6)], [(1,2,1)], [(6,3,7)], [(7,8,9)]],[[(2,3,6)], [(4,5,6)], [(1,2,1)], [(6,3,7)], [(7,8,9)]],[[(2,3,6)], [(4,5,6)], [(1,2,1)], [(6,3,7)], [(7,8,9)]],[[(2,3,6)], [(4,5,6)], [(1,2,1)], [(6,3,7)], [(7,8,9)]]]]], dtype=str)

print(array_5d)

[[[[[['2' '3' '6']]

    [['4' '5' '4']]

    [['1' '2' '1']]

    [['6' '3' '7']]

    [['7' '8' '9']]]


   [[['2' '3' '6']]

    [['4' '5' '6']]

    [['1' '2' '1']]

    [['6' '3' '7']]

    [['7' '8' '9']]]


   [[['2' '3' '6']]

    [['4' '5' '6']]

    [['1' '2' '1']]

    [['6' '3' '7']]

    [['7' '8' '9']]]


   [[['2' '3' '6']]

    [['4' '5' '6']]

    [['1' '2' '1']]

    [['6' '3' '7']]

    [['7' '8' '9']]]


   [[['2' '3' '6']]

    [['4' '5' '6']]

    [['1' '2' '1']]

    [['6' '3' '7']]

    [['7' '8' '9']]]]]]


In [78]:
#tipo de datos de mmi arreglo
array_3d.dtype.name

'str64'

In [85]:
#convertir de un tipo de dato a otro
array_5d.astype(np.float16)

array([[[[[[2., 3., 6.]],

          [[4., 5., 4.]],

          [[1., 2., 1.]],

          [[6., 3., 7.]],

          [[7., 8., 9.]]],


         [[[2., 3., 6.]],

          [[4., 5., 6.]],

          [[1., 2., 1.]],

          [[6., 3., 7.]],

          [[7., 8., 9.]]],


         [[[2., 3., 6.]],

          [[4., 5., 6.]],

          [[1., 2., 1.]],

          [[6., 3., 7.]],

          [[7., 8., 9.]]],


         [[[2., 3., 6.]],

          [[4., 5., 6.]],

          [[1., 2., 1.]],

          [[6., 3., 7.]],

          [[7., 8., 9.]]],


         [[[2., 3., 6.]],

          [[4., 5., 6.]],

          [[1., 2., 1.]],

          [[6., 3., 7.]],

          [[7., 8., 9.]]]]]], dtype=float16)

In [84]:
#convertir de un tipo de dato a otro
array_5d.astype(str)

array([[[[[['2', '3', '6']],

          [['4', '5', '4']],

          [['1', '2', '1']],

          [['6', '3', '7']],

          [['7', '8', '9']]],


         [[['2', '3', '6']],

          [['4', '5', '6']],

          [['1', '2', '1']],

          [['6', '3', '7']],

          [['7', '8', '9']]],


         [[['2', '3', '6']],

          [['4', '5', '6']],

          [['1', '2', '1']],

          [['6', '3', '7']],

          [['7', '8', '9']]],


         [[['2', '3', '6']],

          [['4', '5', '6']],

          [['1', '2', '1']],

          [['6', '3', '7']],

          [['7', '8', '9']]],


         [[['2', '3', '6']],

          [['4', '5', '6']],

          [['1', '2', '1']],

          [['6', '3', '7']],

          [['7', '8', '9']]]]]], dtype='<U1')

operadores matematicos

In [93]:
#array de ejemplos
array4=np.random.random((4,4,2))
array4

array([[[0.54156924, 0.14686827],
        [0.77999606, 0.13513704],
        [0.36850194, 0.16706814],
        [0.50429229, 0.70127944]],

       [[0.86459556, 0.21860809],
        [0.23086531, 0.05052303],
        [0.04513074, 0.19661977],
        [0.88262293, 0.54947236]],

       [[0.46096951, 0.28859605],
        [0.38209059, 0.75455174],
        [0.2405377 , 0.26717038],
        [0.45788214, 0.5273288 ]],

       [[0.181614  , 0.61136489],
        [0.61201788, 0.38405352],
        [0.21744009, 0.38728924],
        [0.72379875, 0.54684414]]])

In [94]:
#array
array5=np.random.random((4,4,2))
array5

array([[[0.76893492, 0.47239975],
        [0.59849416, 0.95428966],
        [0.36459713, 0.79293166],
        [0.78958605, 0.26494016]],

       [[0.37947774, 0.53990432],
        [0.89088936, 0.82656547],
        [0.06686195, 0.26661269],
        [0.41605447, 0.996638  ]],

       [[0.75156944, 0.13885993],
        [0.45914934, 0.18825501],
        [0.2528177 , 0.6456977 ],
        [0.31959084, 0.11531389]],

       [[0.31063792, 0.44844927],
        [0.57509998, 0.26955299],
        [0.21628743, 0.35657545],
        [0.8851467 , 0.2786237 ]]])

In [95]:
array3=np.random.random((4,4,2))

In [98]:
#suma
array6=array3+array4+array5
array4

array([[[0.54156924, 0.14686827],
        [0.77999606, 0.13513704],
        [0.36850194, 0.16706814],
        [0.50429229, 0.70127944]],

       [[0.86459556, 0.21860809],
        [0.23086531, 0.05052303],
        [0.04513074, 0.19661977],
        [0.88262293, 0.54947236]],

       [[0.46096951, 0.28859605],
        [0.38209059, 0.75455174],
        [0.2405377 , 0.26717038],
        [0.45788214, 0.5273288 ]],

       [[0.181614  , 0.61136489],
        [0.61201788, 0.38405352],
        [0.21744009, 0.38728924],
        [0.72379875, 0.54684414]]])

In [99]:
#orta frma para sumar
arra7=np.add(array3,array4,array5)
arra7

array([[[0.79285078, 1.0629835 ],
        [1.15426897, 0.20567613],
        [0.95418372, 0.23744876],
        [0.90281342, 1.08675101]],

       [[1.65240728, 0.44700467],
        [1.21402165, 0.77632573],
        [0.89357428, 0.3344072 ],
        [1.20699012, 1.49849359]],

       [[0.54058188, 0.59046522],
        [0.5986269 , 1.1098114 ],
        [0.50416429, 0.54814935],
        [0.60902222, 1.28232737]],

       [[0.22899947, 0.85595405],
        [1.2828022 , 0.76780726],
        [0.23220977, 0.91889067],
        [1.53280435, 1.41540082]]])

In [100]:
#resta
arra8=arra7-array6
arra8

array([[[-0.79285078, -1.0629835 ],
        [-1.15426897, -0.20567613],
        [-0.95418372, -0.23744876],
        [-0.90281342, -1.08675101]],

       [[-1.65240728, -0.44700467],
        [-1.21402165, -0.77632573],
        [-0.89357428, -0.3344072 ],
        [-1.20699012, -1.49849359]],

       [[-0.54058188, -0.59046522],
        [-0.5986269 , -1.1098114 ],
        [-0.50416429, -0.54814935],
        [-0.60902222, -1.28232737]],

       [[-0.22899947, -0.85595405],
        [-1.2828022 , -0.76780726],
        [-0.23220977, -0.91889067],
        [-1.53280435, -1.41540082]]])

In [103]:
#Multiplicacion
arradasd9=np.multiply(arra8,array4)
arradasd9

array([[[-0.4293836 , -0.15611855],
        [-0.90032525, -0.02779446],
        [-0.35161855, -0.03967012],
        [-0.45528185, -0.76211614]],

       [[-1.428664  , -0.09771884],
        [-0.28027549, -0.03922233],
        [-0.04032767, -0.06575107],
        [-1.06531716, -0.8233808 ]],

       [[-0.24919177, -0.17040593],
        [-0.22872971, -0.83741013],
        [-0.12127052, -0.14644927],
        [-0.2788604 , -0.67620816]],

       [[-0.04158951, -0.52330026],
        [-0.78509788, -0.29487908],
        [-0.05049171, -0.35587647],
        [-1.10944188, -0.77400365]]])

In [107]:
#resta con funcion
arra10=np.subtract

#diviaion
arra11=np.divide(arra7,array4)
arra11

array([[[ 1.46398784,  7.23766622],
        [ 1.47983948,  1.52198191],
        [ 2.58935878,  1.42126897],
        [ 1.79025823,  1.54966901]],

       [[ 1.91119103,  2.04477637],
        [ 5.258571  , 15.36578025],
        [19.79968079,  1.70078113],
        [ 1.36750369,  2.72715011]],

       [[ 1.17270638,  2.04599206],
        [ 1.56671456,  1.47082214],
        [ 2.09598863,  2.0516846 ],
        [ 1.33008514,  2.43174157]],

       [[ 1.26091309,  1.40007067],
        [ 2.09602077,  1.99921941],
        [ 1.06792527,  2.37262123],
        [ 2.11772174,  2.58830753]]])

In [110]:
#exponente
np.exp(array3)

array([[[1.285672  , 2.49956129],
        [1.45393388, 1.07308651],
        [1.7962152 , 1.07291648],
        [1.48962012, 1.47030752]],

       [[2.19858004, 1.25658355],
        [2.67287944, 2.06638912],
        [2.33600811, 1.14773155],
        [1.38315509, 2.5831801 ]],

       [[1.08286724, 1.35238428],
        [1.24176816, 1.42655103],
        [1.30164206, 1.32442575],
        [1.16315959, 2.12760848]],

       [[1.04852611, 1.27709652],
        [1.95577066, 1.46778393],
        [1.01487929, 1.70165521],
        [2.24567378, 2.38346825]]])

In [112]:
#seno
np.sin(array5)
#coseno
np.cos(array6)
#logaritmo
np.log(array3)

array([[[-1.38118129, -0.08761312],
        [-0.98277006, -2.65158827],
        [-0.53497867, -2.65383729],
        [-0.91999475, -0.95328783]],

       [[-0.23849615, -1.47667181],
        [-0.01698714, -0.32047707],
        [-0.16435174, -1.98204317],
        [-1.12587912, -0.0523241 ]],

       [[-2.53058574, -1.19776157],
        [-1.52999706, -1.03490631],
        [-1.33322161, -1.26947544],
        [-1.88954813, -0.28103943]],

       [[-3.04943962, -1.40817537],
        [-0.39930763, -0.95775425],
        [-4.21517902, -0.63186126],
        [-0.21194944, -0.14092244]]])

COMPARACIONES ENTRE MATRICES

In [113]:
#==
array4==array3

array([[[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]]])

In [114]:
# <
arra11 < 0.5

array([[[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]],

       [[False, False],
        [False, False],
        [False, False],
        [False, False]]])

In [ ]:
# >
array11 >0.5

In [119]:
# <=  /   >=
arra8<=0.1

array([[[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]]])

ESTADISTICAS  Y FUNCIONES

In [122]:
arraya=np.random.random((5,5))
arraya

array([[0.00504912, 0.67323278, 0.81202474, 0.01727735, 0.60315828],
       [0.66114694, 0.7175856 , 0.96374452, 0.45460618, 0.77416173],
       [0.90335286, 0.93500625, 0.50471256, 0.00311131, 0.32149124],
       [0.40803317, 0.36616543, 0.84712123, 0.21183053, 0.16135212],
       [0.83348286, 0.06237884, 0.26699308, 0.17778976, 0.41428798]])

In [125]:
#suma de elemetos
suma_total=array4.sum()

suma_total

TypeError: 'numpy.dtypes.Float64DType' object is not callable

In [126]:
#valor minino - maximo
array6.max()
array6.min()

np.float64(0.4113522532174465)

In [128]:
#maxmo por fila
array6.max(axis=0)
#minimo por columana
array6.min(axis=1)

SyntaxError: incomplete input (ipython-input-128-1019768406.py, line 2)

In [ ]:
#fila acumulada
arra7.cumsum(axis=1)

In [ ]:
#media
np.mean(arra7)

In [ ]:
#mediana
np.median(array3)

In [ ]:
#desviacion estandar

np.std(arra11)

